services:

  frontend:
    image: ghcr.io/ssciwr/heiplanet-frontend:main # this should also change to main soon
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/keys:/etc/nginx/ssl:ro # Mount the certificate directory as read-only
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 25
    networks:
      - heiplanet-network
  db:
    image: postgis/postgis:17-3.5
    restart: always
    shm_size: "512m"
    mem_limit: 2g
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "work_mem=64MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "effective_cache_size=1536MB"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "autovacuum_max_workers=4"
      - "-c"
      - "autovacuum_naptime=10s"
    ports:
      - "5445:5432"
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d heiplanet_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - heiplanet-network

  # FastAPI Application service (Stage 2)
  api:
    image: heiplanet-db
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      frontend:
        condition: service_started
    env_file: ./.env
    volumes:
      - ./heiplanet_db/data/production_config.yml:/heiplanet_db/production.yaml
    command: [ "api" ] # Run FastAPI server
    restart: "no"
    networks:
      - heiplanet-network
    profiles: [ "api" ]

  production-runner:
    image: heiplanet-db
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env
    volumes:
      - ./heiplanet_db/data/production_config.yml:/heiplanet_db/production.yaml
    command: [ "production" ]
    restart: "no" # Run once
    networks:
      - heiplanet-network
    profiles: [ "init" ]

volumes:
  postgres_data:


networks:
  heiplanet-network:
    driver: bridge
